org: sadavir
app: aws-node-express-apisad
service: aws-node-express-apisad
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
