version: "3.9"  # optional since v1.27.0
services:
  database:
    build: ./frontend
    environment:
      DB_URL: mongo://db/vidly

  superdupernuper:
    build: ./backend
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
   
  
volumes:
  logvolume01: {}